### ISSUE TITLE
ASD options are greyed out in validation checker

### ISSUE THREAD

**Issue by popelnuh** [thinkWhere/Roadnet#12]
Reported by Ayrshire Roads Alliance on 07/02/2017

To recreate:
- start roadNet on demo database
- Go To Admin Tab
- Select Validation Report

What happens:
- All options are availble except Validation Checks against ASD

What should happen:
- You should be able to run Validation Checks against ASD.

JIRA: ROAD-180

**Comment by rightway1** [comment]
The validation checks are enabled when Roadnet is configured to support ASD.

1. Close QGIS / Roadnet if running
2. Open the configuration file in a text editor. On Windows this is in:  C:\Users\[username]\.qgis2\python\plugins\Roadnet\Params.xml
3. There should be parameters named RNPolyEdit and RNsrwr as shown below:  
     Setting RNsrwr to "true" will enable the ASD validation checks.  
     Setting RNPolyEdit to "true" will enable the Polygon validation checks.

		<Parameter name="RNPolyEdit">true</Parameter>
		<Parameter name="RNsrwr">true</Parameter>

In investigating this issue, noticed that is these settings are set to false, the form and menu options related to SRWR and Polygons are still shown and enabled.  Only the validation form seems to be actually using these settings.  This should be fixed in the QGIS3 version of the plugin!
